<p >Introduction</p>
Your privacy is essential to us. Here in Just Bake, we believe that privacy is a top priority. We know that you care how information about you is used and shared. Thus, we provide this Privacy Policy to summarize our procedures and practices as regards to information collection and use. This will serve you as a guide in making an intelligent decision in sharing your information with us. By visiting Just Bake, you agree to be bound by this Privacy Policy and hereby accept the procedures and practices stated in this herein.<br />
<p >Coverage</p>
This Privacy Policy applies only within this website and other pages where this policy appears. This would describe and explain how we take care and handle your personal information you shared to us. Our subsidiaries' and joint ventures' privacy policies are similar to those described herein. We make every effort to provide a consistent set of privacy practices throughout the world market or commerce. By accepting the Privacy Policy and the User Agreement in registration, you expressly consent to our collection, storage, use and disclosure of your personal information as described in this Privacy Policy.<br />
<p >Information Collection & How Use</p>
You can surf and get into our sites without disclosing and revealing to us any information of who you are. But once you provide us your personal information, you're no longer an unknown. You hereby then agree to us to collect such personal information and allow us to transfer and store all of that information at our server.<br />
<p >We may collect and store the following information:</p>
 <ul>
<li>all information based on your activities on the sites including but not limited to bidding, buying, selling, item and content you generate or that relates to your account and other information from your interaction with our sites, content, services, and advertising, including computer and connection information, statistics on page views, traffic to and from the sites, ad data, IP address and standard web log information; </li>
<li>contact numbers, address, email address and sometimes financial information, such as credit card or bank account numbers; </li>
<li>shipping, billing and other information you provide to purchase or ship an item; </li>
<li>discussions, chats, dispute resolution, communications through our sites, and communications sent to us; </li>
<li>Information from other companies, such as demographic and navigation data; and other supplemental information from third parties. </li>
</ul>
Our very reason in collecting your personal information is to provide you with the best, safe, smooth, efficient experience. You understand and agree that we may use your personal information to provide the services and customer support you request; to resolve disputes, collect fees, and troubleshoot problems; to prevent potentially prohibited or illegal activities, and enforce our User Agreement; to customize, measure and improve our services, content and advertising; to tell you about our services and those of our corporate family, targeted marketing, service updates, and promotional offers based on your communication preferences.<br />
<p >Disclosure of Information</p>
You agree and allow us for the disclosure of your personal information to enforce our policies, to respond to legal requirements, to protect anyone's rights, property, or safety. The aforementioned information will be disclosed in accordance with applicable laws and regulations. We may also disclose your information to our business partners, affiliates and corporate entities whom you have business transactions.<br />
In an effort to respect your privacy and our ability to keep the community free from bad actors, we will not otherwise disclose your personal information to law enforcement, other government officials, or other third parties without a subpoena, court order or substantially similar legal procedure, except when we believe in good faith that the disclosure of information is necessary to prevent imminent physical harm or financial loss or to report suspected illegal activity.
It should be noted that we don't sell or rent your personal information to third parties for their marketing purposes without your explicit consent.
<br />
<p >Cookies</p>
When you visit our site, we send one or more cookies - small files placed on your hard drive- to your computer or other device that uniquely identifies your browser. We use cookies to improve the quality of our service, including for storing user preferences, improving search results and ad selection, and tracking user trends, such as how people search. We also use cookies in its advertising services to help advertisers and publishers serve and manage ads across the web.<br />
<p >Information Security</p>
We secure your information during transmission by using a system which encrypts information you input. We reveal only a few digits of your credit card numbers when confirming an order. Of course, we transmit the entire credit card number to the appropriate credit card company during order processing. It is important for you to protect against unauthorized access to your password and to your computer. Your information is stored on our server and we use system to protect such information.<br />
<p >Accessing and Updating Personal Information </p>
When you use our services, we make good faith efforts to provide you with access to your personal information and either to correct this data if it is inaccurate or to delete such data at your request if it is not otherwise required to be retained by law or for legitimate business purposes. We ask individual users to identify themselves and the information requested to be accessed, corrected or removed before processing such requests, and we may decline to process requests that are unreasonably repetitive or systematic, require disproportionate technical effort, jeopardize the privacy of others, or would be extremely impractical, or for which access is not otherwise required. In any case where we provide information access and correction, we perform this service free of charge, except if doing so would require a disproportionate effort. Some of our services have different procedures to access, correct or delete users' personal information. We do retain personal information from closed accounts to comply with law, prevent fraud, collect any fees owed, resolve disputes, troubleshoot problems, assist with any investigations, enforce our policies and take other actions otherwise permitted by law.<br />
<p >Third Parties</p>
It should be stressed here that the websites of our advertiser and publisher clients as well as the websites on which we place advertisements or any third party websites linked to one of our sites also may collect information from you for various purposes, including, but not limited to providing advertisements about goods and services likely to be of greater interest to you. Such information may include non-personally identifiable information through the use of Cookies and other technology and any personally identifiable information you may choose to give in registering and transacting with such website. These companies typically use a cookie or third party web beacon to collect this information. Although we choose our business partners and clients carefully, we are not responsible for the privacy practices of such third parties. You should check the applicable privacy policies of such third parties to determine how they handle any information they collect from you. If you disclose your information to others, whether they are bidders, buyers or sellers on our sites or other sites throughout the internet, different rules may apply to their use or disclosure of the information you disclose to them. We encourage you to ask questions before you disclose your personal information to others.<br />
<p >Changes and Amendments</p>
Be it remembered that this Privacy Policy may change from time to time. We may amend this Privacy Policy at any time by posting the amended terms on this site. We will not reduce your rights under this Privacy Policy without your explicit consent, and we expect most such changes will be minor. Regardless, we will post any Privacy Policy changes on this page and, if the changes are significant, we will provide a more prominent notice. All amended terms automatically take effect 30 days after they are initially posted on the site.<br />