<p >Introduction</p>
This Agreement contains the complete terms and conditions that apply to you in joining, buying, bidding, selling and all other activities you will make in our website. By using or shopping from this Web site, you agree to be bound by its terms of use and shall comply thereof. This Agreement describes and encompasses the entire agreement between us and you, and supersedes all prior or contemporaneous agreements, representations, warranties and understandings with respect to the Site, the content and computer programs provided by or through the Site, and the subject matter of this Agreement. Amendments to this agreement can be made and effected by us from time to time without specific notice to you end. Agreement posted on the Site reflects the latest agreement and you should carefully review the same before you use our site.
<p >Use of the site & Prohibitions</p>
The Site allows you to post offers, sell, advertise, bid and shop online. However, you are prohibited to do the following acts, to wit: (a) use our sites, including its services and or tools if you are not able to form legally binding contracts, are under the age of 18, or are temporarily or indefinitely suspended from using our sites, services, or tools (b) posting of an items in inappropriate category or areas on our sites and services; (c) collecting information about users' personal information; (d) maneuvering the price of any item or interfere with other users' listings; (f) post false, inaccurate, misleading, defamatory, or libelous content; (g) take any action that may damage the rating system.<br />
For you to complete the sign-up process in our site, you must provide your full legal name, current address, a valid email address, and any other information needed in order to complete the signup process. You must qualify that you are 18 years or older and must be responsible for keeping your password secure and be responsible for all activities and contents that are uploaded under your account. You must not transmit any worms or viruses or any code of a destructive nature.
<p >Payments and Processes of Invoices</p>
Just Bake has the sole discretion to provide the terms of payment. Unless otherwise agreed, payment must first be received by Just Bake prior to the latter's acceptance of an order. Unless credit term has been agreed upon, payment for the products shall be made by credit card, paypal or wire transfers. Invoices are due and payable within the time period noted on your invoice, measured from the date of the invoice. An order may be invoice separately. Just Bake has all the discretion to cancel or deny orders. Just Bake is not responsible for pricing, typographical, or other errors in any offer by Just Bake and reserves the right to cancel any orders arising from such errors. Invoices must be paid within 15 days of the invoice date. For all but consumer purchases, Just Bake reserves the right to charge you a late penalty charge of 1% per month applied against undisputed overdue amounts or the maximum rate permitted by law whichever is less. Every 30 days thereafter, you will continue to be charged an additional late penalty charge.
<p >Refund Policy</p>
We do not have to provide a refund if you have changed your mind about a particular purchase, so please choose carefully. If the goods are faulty, we will meet our obligations under the applicable laws. However, if "non-faulty" accounts are cancelled within two weeks of the first payment a full refund, will be given."
<p >Risk of Loss</p>
All items purchased from our website are made pursuant to a shipment contract. The risk of loss and title for such items pass to you upon our delivery to the carrier.
<p >Product Pricing & Descriptions</p>
The List Price displayed for products on our website represents the full retail price listed on the product itself, suggested by the manufacturer or supplier, or estimated in accordance with standard industry practice; or the estimated retail value for a comparably featured item offered elsewhere. The List Price is a comparative price estimate and may or may not represent the prevailing price in every area on any particular day. For certain items that are offered as a set, the List Price may represent "open-stock" prices, which means the aggregate of the manufacturer's estimated or suggested retail price for each of the items included in the set. Where an item is offered for sale by one of our merchants, the List Price may be provided by the merchant. In cases of mispriced in our catalogs in which the item's correct price is higher than our stated price, we will, at our discretion, either contact you for instructions before shipping or cancel your order and notify you of such cancellation.
We do not warrant that product descriptions or other content of this site is accurate, complete, reliable, current, or error-free. If a product offered in our website is not as described, your sole remedy is to return it in unused condition.
<p >Editing, Deleting and Modification</p>
We may edit, delete or modify any of the terms and conditions contained in this Agreement, at any time and in our sole discretion, by posting a notice or a new agreement on our site. Your Continued Participation In Our Program, Visit And Shopping In Our Site Following Our Posting Of A Change Notice Or New Agreement On Our Site Will Constitute Binding Acceptance Of The Change.
<p >Acknowledgment of Rights</p>
You hereby acknowledge that all rights, titles and interests, including but not limited to rights covered by the Intellectual Property Rights, in and to the site, and that You will not acquire any right, title, or interest in or to the Program except as expressly set forth in this Agreement. You will not modify, adapt, translate, prepare derivative works from, decompile, reverse engineer, disassemble or otherwise attempt to derive source code from any of our services, software, or documentation, or create or attempt to create a substitute or similar service or product through use of or access to the Program or proprietary information related thereto.<br />
Fraud<br />
Fraudulent Activities are highly monitored in our site and if fraud is detected Just Bake shall resort al remedies available to us, and you shall be responsible for all costs and legal fees arising from these fraudulent activities.<br />
<p >Warranty Disclaimer and Limitations of Liability</p>
We will not be liable for indirect, special, or consequential damages, or any loss of revenue, profits, or data, arising in connection with this Agreement or the Program, even if we have been advised of the possibility of such damages. Further, our aggregate liability arising with respect to this Agreement and the Program will not exceed USD2,000 or the total price of the subject products paid or payable to you whichever is less.<br />
We make no express or implied warranties or representations with respect to the Program or any products sold and offered in our website (including, without limitation, warranties of fitness, merchantability, non-infringement, or any implied warranties arising out of a course of performance, dealing, or trade usage). In addition, we make no representation that the operation of our site will be uninterrupted or error-free, and we will not be liable for the consequences of any interruptions or errors. This site and its information, contents, materials, products and services are provided on an "as is" and "as available" basis. You and understand and agree that your use of this site is at your own risk.
<p >Confidentiality</p>
You agree not to disclose information you obtain from us and or from our clients, advertisers and suppliers. All information submitted to by an end-user customer pursuant to a Program is proprietary information of Just Bake. Such customer information is confidential and may not be disclosed. Publisher agrees not to reproduce, disseminate, sell, distribute or commercially exploit any such proprietary information in any manner.
<p >Non-Waiver</p>
Failure of the Just Bake to insist upon strict performance of any of the terms, conditions and covenants hereof shall not be deemed a relinquishment or waiver of any rights or remedy that the we may have, nor shall it be construed as a waiver of any subsequent breach of the terms, conditions or covenants hereof, which terms, conditions and covenants shall continue to be in full force and effect.<br />
No waiver by either party of any breach of any provision hereof shall be deemed a waiver of any subsequent or prior breach of the same or any other provision
<p >Miscellaneous</p>
This Agreement shall be governed by and construed in accordance with the substantive laws of Bangalore, without any reference to conflict-of-laws principles.<br />
Any dispute, controversy or difference which may arise between the parties out of, in relation to or in connection with this Agreement is hereby irrevocably submitted to the exclusive jurisdiction of the courts of Bangalore, to the exclusion of any other courts without giving effect to its conflict of laws provisions or your actual state or country of residence.<br />
The entire agreement between the parties with respect to the subject matter hereof is embodied on this agreement and no other agreement relative hereto shall bind either party herein.<br />
Your rights of whatever nature cannot be assigned nor transferred to anybody, and any such attempt may result in termination of this Agreement, without liability to us. However, we may assign this Agreement to any person at any time without notice.<br />
In the event that any provision of these Terms and Conditions is found invalid or unenforceable pursuant to any judicial decree or decision, such provision shall be deemed to apply only to the maximum extent permitted by law, and the remainder of these Terms and Conditions shall remain valid and enforceable according to its terms.<br />